### ISSUE TITLE
No such file or directory error when running docker-compose up

### ISSUE THREAD

**Issue by gkinsman** [pardahlman/docker-rabbitmq-cluster#1]
Hi there!

I'm taking this repo for a whirl to test out some rabbitmq clustering locally, and I'm hitting a bit of a snag that I can't quite work out.

I cloned the repo, ran `docker-compose up`, and got the following output:

```
PS C:\Projects\Work\RabbitClustering\docker-rabbitmq-cluster> docker-compose up
Starting docker-rabbitmq-cluster_rabbitmq1_1 ... done
Starting docker-rabbitmq-cluster_rabbitmq3_1 ... done
Starting docker-rabbitmq-cluster_rabbitmq2_1 ... done
Attaching to docker-rabbitmq-cluster_rabbitmq1_1, docker-rabbitmq-cluster_rabbitmq2_1, docker-rabbitmq-cluster_rabbitmq3_1
rabbitmq2_1  | standard_init_linux.go:190: exec user process caused "no such file or directory"
rabbitmq3_1  | standard_init_linux.go:190: exec user process caused "no such file or directory"
docker-rabbitmq-cluster_rabbitmq2_1 exited with code 1
docker-rabbitmq-cluster_rabbitmq3_1 exited with code 1
```

So the first node appears to start, but the second and third fail, and hence haproxy along with it. It looks like the official image hasn't changed either. The failure appears to be in locating the rabbit image's entrypoint: `/usr/local/bin/docker-entrypoint.sh`

Any ideas on what I'm missing? 😕 

Thanks!

**Comment by pardahlman** [comment]
Hi there, it sounds like you might have problem with the [volume mapping](https://github.com/pardahlman/docker-rabbitmq-cluster/blob/master/docker-compose.yml#L22). Have you [shared the drive](https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/) that contains the source code with docker?

**Comment by gkinsman** [comment]
Ah,

You were right - the volume mapping refused to work with docker, and turns out to be an issue with Docker itself if you're logged into windows with a non-local account - in my case I was logged in with a Microsoft account.

A recent format and reinstall fixed the issue, and works beautifully now! Thanks!
